name = "indo" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "shopee.co.id.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "www.ruangguru.com.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "gomarketplacefront-cf.zoom.us.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "englishtest-stage-7.duolingo.com.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
pattern = "blog.sushiroll.co.id.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "acces.iflix.com.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "104.22.25.131.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "ruangguru.com.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "104.26.7.171.indo.bjhonnstore.filegear-sg.me"
custom_domain = true
[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "1f88cb38-cd4c-454d-8576-f88f35153662"
