name = "sg-xcl-oracle" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "oxcl.crotjanda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.oxcl.crotjanda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "care.pmang.game.naver.com.oxcl.crotjanda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "bill.neowiz.com.oxcl.crotjanda.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.oxcl.crotjanda.filegear-sg.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "ba000bef-7937-4df8-86f1-533d943e8ac7"
