name = "sg-bytevirt-abscell" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "cms.ruangguru.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "gw.ruangguru.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "df.game.naver.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "account.pmang.game.naver.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "care.pmang.game.naver.com.sg5.abscell.my.id"
custom_domain = true
[[routes]]
pattern = "app-stg.gopay.co.id.sg5.abscell.my.id"
custom_domain = true
[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "73c26ff5-b594-4444-8232-fe3dca1c8c3a"
