name = "Tencent Cloud Computing SG" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "teams.microsoft.com.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "meetings.googleapis.com.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "beta.zoom.us.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "api.zoom.us.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "store.zoom.us.tccsg.hashoino.filegear-sg.me"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.tccsg.hashoino.filegear-sg.me"
custom_domain = true


[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "f0f83b69-ec7f-4814-af8f-af38f8721c91"
