name = "oraqle" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "oraqle.envy-cloud.me"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.oraqle.envy-cloud.me"
custom_domain = true
[[routes]]
pattern = "support.duolingo.com.oraqle.envy-cloud.me"
custom_domain = true
[[routes]]
pattern = "error.growmotion.com.oraqle.envy-cloud.me"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "fa39d7f9-1a82-49ee-82a0-6d9712a61348"
