name = "fadtech4" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "ava.game.naver.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "blog.webex.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.sushiroll.co.id.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "blog.sushiroll.co.id.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "cdn.appsflyer.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "investor.fb.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "investors.spotify.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.joox.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "zoomcares.zoom.us.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "graph.facebook.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "www.help.tinder.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "poe.garena.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "games.axis.co.id.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "api.ovo.id.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "cdnodeb.visionplus.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "104.26.6.171.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "app.gopay.co.id.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "go.appsflyer.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "devsupport.webex.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "edu.ruangguru.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "fadz.ngapaktunnelling.xyz.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "creativeservices.netflix.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "npca.netflix.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true
[[routes]]
pattern = "gw.ruangguru.com.fadtech4.ngapaktunnelling.xyz"
custom_domain = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "4819b8b0-6a33-4c6c-8d33-c0947ecbe803"
